### ISSUE TITLE
Неплохо бы добавить возможность печати в чеке произвольных данных

### ISSUE THREAD

**Issue by ilcommm** [Komtet/komtet-kassa-php-sdk#17]
Мы хотим, чтобы CRM могла отправлять команду на печать каких-то наших маркетинговых акций например, или реквизиты доступа в ЛК на нашем сайте.

**Comment by elatonsev** [comment]
Вы можете настраивать внешний вид чека из драйвера вашей ККТ. Изменить заголовок, добавить произвольный текст после основной информации чека.

**Comment by ilcommm** [comment]
если заголовок достаточно менять из чека, то произвольную инфу было бы очень круто печатать именно из CRM. Т.к. можно будет допечатывать что-то реально персональное (личные скидки, реквизиты доступа итп), а не инфу для всех.

**Comment by elatonsev** [comment]
Наш сервис поддерживает оборудование от разных производителей, на текущий момент в API мы принимаем только данные по протоколу ФФД 1.0.5, необходимые для записи на фискальный накопитель, они едины для всех ККТ.
Думаю, Вашу задачу можно решить и другими сопсобами, например через отправку обычного email.
