### ISSUE TITLE
Заголовок на чеке хорошо бы сделать управляемым

### ISSUE THREAD

**Issue by ilcommm** [Komtet/komtet-kassa-php-sdk#18]
ТОРГОВЫЙ ОБЪЕКТ
ДОБРО ПОЖАЛОВАТЬ
- плохо соотносится с нашим брендом. Хотелось бы бОльшей персонализации, в идеале управляемой нашей CRM.

**Comment by ilcommm** [comment]
Сюда же вопрос - спасибо за покупку - хорошо бы редактировать получить возможность.

**Comment by elatonsev** [comment]
Вы можете настраивать внешний вид чека из драйвера вашей ККТ. Изменить заголовок, добавить произвольный текст после основной информации чека.

**Comment by ilcommm** [comment]
производитель нам об этом не рассказал(. Закрываю тикет, буду разбираться, спасибо!
