### ISSUE TITLE
Версия ФФД

### ISSUE THREAD

**Issue by lashnag** [Komtet/komtet-kassa-php-sdk#20]
Добрый день! Надо написать что обязательно, что нет в какой версии ФФД. У Вас в README написано, что большинство опционально, например setCalculationMethod. Но мне кажется, что для версии ФФД 1.05, вероятно это уже обязательные поля. Вам нужно как-то обозначить список обязательных параметров (кроме того, не написано ничего про ФФД 1.1 - вы еще не готовы?)

**Comment by elatonsev** [comment]
Добрый день! 
Все поля опциональны, из обязательных добавляется только ИНН Кассира, но мы предусмотрели возможность задать его из личного кабинета.

Если вы выполняете только полные расчеты за покупку, то менять ничего не нужно, если же возможны авансовые платежи или кредит, то необходимо передавать эти атрибуты в позиции в соответствии с описанием API (ну или через соответствующие методы SDK) https://kassa.komtet.ru/integration/api#tag/Fiskalizaciya-platezhej%2Fpaths%2F~1kassa.komtet.ru~1api~1shop~1v1~1queues~1%7Bqueue_id%7D~1task%2Fpost
