### ISSUE TITLE
Несовместимость версий

### ISSUE THREAD

**Issue by lashnag** [Komtet/komtet-kassa-php-sdk#21]
Коллеги, добрый день! Хотел бы попросить Вас придерживаться семантического версионирования:
https://semver.org/lang/ru/

Если ему следовать, то у Вас не стабильный пакет (версия 0.X.X). У меня стояла версия ^0.6.0 в composer. Я обновил до ^0.9.0, чтобы пользоваться новыми возможностями SDK. У меня сломалась возможность отправлять чеки - значит, что обратная совместимость сломана. Если вы имели ввиду, что ни за что не отвечаете версией 0 - тогда зачем вы клиентам предлагаете пользоваться SDK? Версия 0.X.X не предназначена для продакшена.

Call to undefined method Komtet\KassaSdk\Payment::createCard()

Алексей, ООО Платрон

**Comment by lashnag** [comment]
А при несовместимости версий принято писать при установке composer инструкцию для перехода

**Comment by elatonsev** [comment]
Добрый день! 
Благодарю за этот комментарий, мы не досмотрели, наша ошибка, впредь постараемся внимательней относиться к версионированию пакетов.

Выпустили патч 0.9.1, возвращающий совместимость с версиями 0.X.X.
Выпустили релиз 1.0.0 с обновленной версией пакета. Изменения опубликованы в описании к релизу.

**Comment by lashnag** [comment]
Вы хотите сказать что будет работать и new Payment(Payment::TYPE_CARD, 4815) и Payment::createCard? Я уже выкачал 0.9.0 и пользуюсь new Payment(Payment::TYPE_CARD, 4815).

**Comment by elatonsev** [comment]
Да, будут работать оба варианта. Мы выпустили релиз 0.9.1 чтобы подобная ситуация не повторилась у кого-нибудь еще.
