### ISSUE TITLE
Возможность указать payment_address в статических методах

### ISSUE THREAD

**Issue by imfurman** [Komtet/komtet-kassa-php-sdk#30]
Есть статические хелперы вызова конструктора, но внутри них не передать payment_address, поэтому приходиться напрямую вызывать конструктор класса Check и уже там пробрасывать payment_address.

![image (1)](https://user-images.githubusercontent.com/6038796/56136992-8f95b200-5f9c-11e9-92ba-daa4049c73f0.png)

**Comment by elatonsev** [comment]
Спасибо за Ваш комментарий, в скором времени исправим.

**Comment by mini4** [comment]
#32 Расширенны возможности статических функций приемом адреса места расчета. Уже доступно в версии [2.0.2](https://github.com/Komtet/komtet-kassa-php-sdk/releases/tag/2.0.2)
