### ISSUE TITLE
Как работает discount в Position?

### ISSUE THREAD

**Issue by hunty** [Komtet/komtet-kassa-php-sdk#43]
Уважаемые разработчики, уточните пожалуйста, как работает discount в  Position?
Применяется ли сумма скидки к сумме позиции, или же к каждому товару?
Например для скидки в 20 руб для двух товаров ценой 240 руб:
`new Position('test', 240.0, 2, 480, 20.0, 0)`
в итоге сумма позиции будет:  480 - 20 = 460 или 480 - 2 * 20 - 440 ?

**Comment by elatonsev** [comment]
Добрый день.
Извиняюсь за долгий ответ.
Параметр discount на текущий момент является утаревшим и не обрабатывается сервером, в скором времени мы его удалим из SDK с поднятием версии.

Скидка вычисляется разницей price * quantity - total. Т.е. в total нужно передать стоимость с примененной скидкой.
Для Вашего примера: 
price = 240
quantity = 2
total = 460
