### ISSUE TITLE
Ошибка excise: None is not of type number

### ISSUE THREAD

**Issue by alekciy** [Komtet/komtet-kassa-php-sdk#44]
При работе с сервисом через SDK v2.3.3 возникат ошибка `positions->0->excise: None is not of type number`. Но у меня нет акцизных сборов, поэтому метод Position::setExcise не вызывается и остается в дефолтном значении null https://github.com/Komtet/komtet-kassa-php-sdk/blob/master/src/Position.php#L67

Возможно стоит его инициировать нулем.

**Comment by alekciy** [comment]
В QueueManager::putCheck происходит вызов $check->asArray() которые и формирует для curl поле `excise`.

**Comment by alekciy** [comment]
Подготовил https://github.com/Komtet/komtet-kassa-php-sdk/pull/45

**Comment by keipaglows** [comment]
Спасибо за пул реквест! Сейчас выкатим общий хотфикс с другими правками, включаю вашу.

**Comment by keipaglows** [comment]
Готово.
