### ISSUE TITLE
Методы для УРЛ нотификации

### ISSUE THREAD

**Issue by kirc0de** [Komtet/komtet-kassa-php-sdk#5]
Не нашёл в библиотеке и в ридми-файле информации о методах для работы с УРЛ нотификации. Речь об отчётах после фискализации чека.

Какие есть методы работы с этим и какие примеры кода есть?

**Comment by ghost** [comment]
В библиотеке этого нет. Можно посмотреть, как это сделано в модуле для opencart:
https://github.com/Komtet/komtet-kassa-opencart/blob/master/upload/catalog/controller/extension/module/komtet_kassa.php

Или в bitrix: https://github.com/Komtet/komtet-kassa-bitrix/blob/master/komtet.kassa/install/tools/komtet_kassa_report_handler.php
