### ISSUE TITLE
Тег 1162 маркировка

### ISSUE THREAD

**Issue by lashnag** [Komtet/komtet-kassa-php-sdk#58]
Добрый день! Не могли бы вы добавить тег 1162 в SDK? Параметр называется nomenclature_code в вашем API. Так же вопрос - в каком виде надо вставлять код товара

**Comment by elatonsev** [comment]
@lashnag Здравствуйте!
У позиции чека есть метод  `setNomenclature`
https://github.com/Komtet/komtet-kassa-php-sdk/blob/master/src/Position.php#L203

В код требуется передавать данные считанные с DataMatrix марки:
```
"nomenclature_code": {
	"code": "010460406000600021N4N57RSCBUZTQ\u001d2403004002910161218\u001d1724010191ffd0\u001d92tIAF/YVoU4roQS3M/m4z78yFq0fc/WsSmLeX5QkF/YVWwy8IMYAeiQ91Xa2z/fFSJcOkb2N+uUUmfr4n0mOX0Q==."
}
```

Единственное, нам нужно убрать из класса Nomenclature атрибут type, т.к. он теперь стал необязательным, поправим в ближайшее время.
https://github.com/Komtet/komtet-kassa-php-sdk/blob/master/src/Nomenclature.php

**Comment by lashnag** [comment]
Простите, искал в позиции, но проглядел

**Comment by lashnag** [comment]
А не подскажете как такой формат получить из набора байт типа 45 0D 04 30 77 19 57 61? В других онлайн кассах требуют какой-то набор бит. Не знаете - это та же информация, просто в разном формате?

**Comment by elatonsev** [comment]
@lashnag общие рекомендации выглядят так https://xn--80ajghhoc2aj1c8b.xn--p1ai/upload/iblock/4f1/formirovanie-tega-1162-na-KKT.pdf

Носители маркировки могут быть разные - от штрих-кодов до RFID меток, а на фискальный накопитель они все должны записаться в едином бинарном формате.  

Кассовое оборудование и сервисы фискализации могут хотеть получить на вход как код в чистом виде (считанный с марки), так и уже трансформированную битовую последовательность, по алгоритму, который я скинул выше.

Т.к. наш сервис поддерживает разные кассы, мы принимаем на вход изначальный код маркировки и передаем его на оборудование в зависимости от требований производителя.

Стоит отметить что обратная конвертация из бинарного кода в строку возможна лишь с потерей параметров, т.к. при формировании бинарного кода часть параметров отбрасывается.

**Comment by lashnag** [comment]
А что такое изначальный код маркировки в чистом виде? Если маркировка бывает разная - то как мне понять после получения что это за маркировка была для того, чтобы ее преобразовать к формату онлайн кассы?

**Comment by lashnag** [comment]
Я правильно понимаю, что такой способ только для табачной продукции?
http://nilsoft.ru/wp-content/uploads/Otherdocs/1162_cig.pdf
При маркировке другой продукции результат считывания будет другой?

**Comment by elatonsev** [comment]
В документе, который я приложил выше, как раз есть примеры считанных последовательностей в зависимости от типа носителя и результаты их преобразования в тег 1162.
