### ISSUE TITLE
Чек коррекции?

### ISSUE THREAD

**Issue by nochek07** [Komtet/komtet-kassa-php-sdk#6]
Не подскажите когда появится чек коррекции?

**Comment by elatonsev** [comment]
Возможность провести чек коррекции из личного кабинета появится с ближайшим релизом, ориентировочно 5-7 дней. Так же будет возможность оформить чек коррекции через API, напишите запрос на нашу почту поддержки, как выйдет релиз, я опишу как выполнить интеграцию.
