### ISSUE TITLE
Обновить версию psr/log

### ISSUE THREAD

**Issue by yenyasinn** [Komtet/komtet-kassa-php-sdk#77]
В данный момент в composer.json прописана зависимость `"psr/log": "^1.0"`. Эта зависимость конфликтует с другими проектами, которые требуют psr/log версий 2 или 3.

Рассмотрите пожалуйста возможность изменить зависимость, чтобы было возможно установить проект с разными версиями psr/log.

**Comment by efremchev** [comment]
Исправлено в версии 10.0.0
