### ISSUE TITLE
Исправить "Deprecated function: Creation of dynamic property" в ApiValidationException->__construct()

### ISSUE THREAD

**Issue by yenyasinn** [Komtet/komtet-kassa-php-sdk#78]
При отправке запроса, например putCheck, если вызывается исключение ApiValidationException, то появляется ошибка в версии 9.1.2

Deprecated function: Creation of dynamic property Komtet\KassaSdk\Exception\ApiValidationException::$vldCode is deprecated in Komtet\KassaSdk\Exception\ApiValidationException->__construct() (line 20 of /var/www/html/vendor/komtet/kassa-sdk/src/Exception/ApiValidationException.php).
Komtet\KassaSdk\Exception\ApiValidationException->__construct('Ошибка авторизации', 'AUT00', 'Проверьте правильность написания идентификатора магазина и его секрета', 403) (Line: 173)

**Comment by efremchev** [comment]
Исправлено в версии 10.0.0
