### ISSUE TITLE
Using exception in SDK

### ISSUE THREAD

**Issue by lashnag** [Komtet/komtet-kassa-php-sdk#9]
Yoy need to use ClientException instead \LogicException and \InvalidArgumentException. Otherwise i can't catch your exceptions and share with my project excetions

**Comment by ghost** [comment]
Можно по-русски. Здесь только коммиты в основном на английском.

Я так понимаю речь идёт об исключениях в `QueueManager` и `Vat`.
`ClientException` не подойдёт, я думаю. Оно для обозначения ошибок при взаимодействии с сервером предназначено. Есть интерфейс `SDKException`, можно отлавливать его. Нужно только придумать название для нового исключения, которое будет его реализовывать и заменить упомянутые исключения на него. 
Буду благодарен за pull-request.

**Comment by lashnag** [comment]
Коллеги, закрывайте Issues, пожалуйста. А то создается впечатление, что SDK не поддерживается
